//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Al_Wakel_Pro_move_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Center
    {
        public Center()
        {
            this.Operation = new HashSet<Operation>();
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Adderss { get; set; }
    
        public virtual ICollection<Operation> Operation { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
