//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Al_Wakel_Pro_move_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.Operation = new HashSet<Operation>();
        }
    
        public string Name { get; set; }
        public decimal PurchasingPrice { get; set; }
        public decimal SellingPrice { get; set; }
        public int Id { get; set; }
    
        public virtual ICollection<Operation> Operation { get; set; }
    }
}
