//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Al_Wakel_Pro_move_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<int> CenterId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Difference { get; set; }
        public int CustomerId { get; set; }
    
        public virtual Center Center { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual User User { get; set; }
    }
}
