//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Al_Wakel_Pro_move_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Operation = new HashSet<Operation>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public int IdentityNumber { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> CenterId { get; set; }
    
        public virtual Center Center { get; set; }
        public virtual ICollection<Operation> Operation { get; set; }
    }
}
