//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Al_Wakel_Pro_move_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyExchange
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeAndDate { get; set; }
        public Nullable<int> CurrencyFromId { get; set; }
        public Nullable<int> CurrencyToId { get; set; }
        public decimal QuantityFrom { get; set; }
        public decimal QuantityTo { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
    }
}
