//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Al_Wakel_Pro_move_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyOperations
    {
        public int Id { get; set; }
        public string OperationsType { get; set; }
        public int CurrencyId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CenterId { get; set; }
        public System.DateTime OperationDate { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual Center Center { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual User User { get; set; }
    }
}
